# Generated by Django 2.2.3 on 2019-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cartid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
