# Generated by Django 2.2.3 on 2019-08-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20190805_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
