# Generated by Django 2.2.3 on 2019-08-03 15:07

from django.db import migrations, models
import siteSettings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('shortCompany', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField()),
                ('crn', models.CharField(blank=True, max_length=60, null=True)),
                ('vat', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('adminEmail', models.CharField(blank=True, max_length=20, null=True)),
                ('contactEmail', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=siteSettings.models.upload_image_path)),
                ('logo_mini', models.ImageField(blank=True, null=True, upload_to=siteSettings.models.upload_image_path)),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('instagram', models.CharField(blank=True, max_length=120, null=True)),
                ('youtube', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
