# Generated by Django 2.2.3 on 2019-08-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='siteSettings',
            new_name='siteSetting',
        ),
    ]
