# Generated by Django 2.2.3 on 2019-08-07 12:20

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190807_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('product', models.ForeignKey(default=None, on_delete='CASCADE', to='products.Product')),
            ],
        ),
    ]
