# Generated by Django 2.2.3 on 2019-08-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='pImage',
        ),
    ]
