# Generated by Django 2.2.3 on 2019-08-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190807_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pImage',
            new_name='Imagep',
        ),
    ]
