# Generated by Django 2.2.3 on 2019-08-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190807_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortdesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
